name: Run Ansible Playbook on Ansible Master
 
on:
  workflow_dispatch:  # manual trigger
  push:
    branches:
      - master  # trigger on push to master
 
jobs:
  ping-servers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
 
    - name: Setup SSH to ansible-master
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.GCP_SSH_HOST }} >> ~/.ssh/known_hosts
 
    - name: Ping Ansible managed servers
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_SSH_HOST }} \
          "ansible servers -m ping -i /etc/ansible/hosts"
 
    - name: Run Ansible Playbook
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_SSH_HOST }} \
          "ansible-playbook -v /home/gcp_phase2_id6/playbooks/install_apache.yml -i /etc/ansible/hosts"
